name: "sprint"
version: "1.0.0"

profile: "sprint"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sprint:
    staging:
      +schema: stage
    marts:
      +schema: mart

seeds:
  +schema: dim
